### ISSUE TITLE
IPFS Hello Zuidhorn Service

### ISSUE THREAD

**Issue by jastam** [teamforus/api.forus.io-ipfs#2]
- [x] Implement HTTP api
- [x] Write api documentation
- [x] Connect http api to IPFS storage
- [x] Add app to docker container
- [x] Run container on AWS

**Comment by jastam** [comment]
API documentation can be found at: https://jastamtest.docs.apiary.io.

**Comment by jastam** [comment]
- [ ] add name to message
- [ ] keep list of previous messages
- [ ] add listing of previous messages to the api

**Comment by jastam** [comment]
A docker image is available as jastam/ipfs-api

**Comment by dev-weget** [comment]
- [ ] Reverse messages order on the API

**Comment by martijndoornik** [comment]
I have tested this service and it done
